# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: fobia
# "service" is the name of this project. This will also be added to your AWS resource names.
service: aws-crud-serverless

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  provider:
    stage: ${opt:stage, 'dev'}
  # Uncomment to easily set up a custom domain. Read the docs for more details:
  # https://www.serverless.com/framework/docs/providers/aws/guide/domains
  # domain: api.example.com

functions:
  createItem:
    handler: src/handlers/createItem.handler
    events:
      - httpApi:
          path: /items
          method: post
