name: Deploy Serverless API

on:
  push:
    branches:
      - main  #prod
      - dev   #dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment: ${{ github.ref_name == 'main' && 'SLS Guru' || 'SLS Guru DEV' }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Install Serverless
        run: npm install -g serverless

      - name: Debug branch #DEBUG STEP
        run: |
          echo "GITHUB_REF: $GITHUB_REF"
          echo "GITHUB_REF_NAME: $GITHUB_REF_NAME"

      - name: Deploy to AWS
        run: |
          if [ "${GITHUB_REF##*/}" = "main" ]; then
            echo "Deploying to PROD"
            serverless deploy --stage prod
          elif [ "${GITHUB_REF##*/}" = "dev" ]; then
            echo "Deploying to DEV"
            serverless deploy --stage dev
          fi
        env:
          # Required for AWS deployment credentials
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          # Required for Serverless Framework v4 authentication
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
          SERVERLESS_LICENSE_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}